### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by YotamGit** [YotamGit/recipe-app#1]
https://image.online-convert.com/convert-to-svg

TODO
- [x] try to reconnect to db if the first attempt failed.
- [x] send proper errors if db is down 
- [x] use winston for logging to console and db https://github.com/winstonjs/winston https://betterstack.com/community/guides/logging/how-to-install-setup-and-use-winston-and-morgan-to-log-node-js-applications/

#animations
- [ ] https://medium.com/hackernoon/5-ways-to-animate-a-reactjs-app-in-2019-56eb9af6e3bf
# Features
- [ ] comment system for recipes
- [ ] option to filter recipes with multiple categories
- [x] share recipes
- [ ] request edit permission to recipe(multiple editors and 1 owner)
- [x] add private recipe option
- [x] add approved field to recipe
- [x] add notes to recipe.
- [x] click on a users name to go to their page and see their recipes.
- [x] when adding a new recipe, add option to make the recipe private or public.
public: the recipe is visible when visiting one's profile.
private: only owner can view the recipe.
when selecting public, add option to submit the recipe for moderator approval. after approval the recipe is visible on main page.
- - [x] when a change is made to an approved public recipe it needs to be re-approved. 
- - [x] users cannot view or favorite a private recipe.
- - [x] if a user changes the visibility of a recipe to private, it is automatically unapproved. 
- [x] user profile:
- - [x] users favorite recipes, 
- - [x] users personal recipes(public not authorized recipes)
- - [x] add option to search/filter those recipes 

### emails
- [x] on sign up
- [x] on recipe approval/disapproval
- [x] password reset
- [x] https://www.courier.com/blog/how-to-send-emails-with-node-js/

# Storage
- [x] how should i save the recipes
- [x] where

# Data
- [x] id
- [x] title
- [x] category
- [x] creation time (timestamp)
- [x] last updated (timestamp)
- [x] description (string markdown)
- [x] ingredients (string markdown)
- [x] instructions (string markdown)

# Styling
- [x] add button tooltips everywhere
- [x] recipes main page
- [x] recipe editor
- [x] recipe expanded page
- [x] app bar
- [x] app bar menu
- [x] recipe card
- [x] login page
- [x] signup page

# Authentication
- [x] username ~and password~

# server stuff
- [x] add https
- [x] add default routs to pages of react project
- [x] upload script 

# Components
- [x] search bar
- [x] button
- [x] recipe
- [x] recipe card:
- - [x] ~color chips~
- - [x] put image
- [x] recipe page:
 - - [x] redesign additional information
- - [x] add photo
- - [x] size ratios
- [x] lore
- [x] ingredients
- [x] instructions
- [x] markdown editor with preview https://marked.js.org/ --- when saving the edited stuff send it to parent and store it untill user selects to submit all edits. then send the markdown from all of the editors to the server
* disable confirm prompt on edit
- [x] popups  npm install reactjs-popup
- [x] recipe editor:
* add additional data prompts
* add photo upload
* add hebrew titles option
- [x] category dropdown

# Utility - front
- [x] create new recipe: 
* create new add recipe component
* reuse the recipe editor with a blank recipe and maybe modify the recipe editor to work when the recipe is blank if the component breaks.
- [x] delete recipe
- [x] change recipe
- [x] upload photo
- [x] search recipes
- [x] filter recipes by category
- [x] add toggle dir rtl to editor --- each editor has a rtl bool and if its not false when it returns to parent recipe editor then the main rtl var will be changed to true.
- [x] in editor, create a helping toolbar that offers shortcuts to markdown strings (- [ ], ---, ###, etc...) and appends it to the end of the textbox.
- [x] markdown help button https://commonmark.org/help/
- [x] export to print button 
- - [x] add basic native print button
- - [x] add custom styling to print
- [x] add share button to recipe and recipecard

# Front Alerts
- [x] create global alerts that receive a text and severity and displays an alert for a set duration
- [x] replace window.alert with custom alerts using mui alerts
- [ ] 

# Users:
- [x] user based login
- [x] each user can sign up with his own password
- [x] add option to retrieve lost password(?)
- [x] each recipe has a creator
- [x] each recipe has an array of users that liked the recipe
- [x] add a user collection to db
- [x] validate username
- [x] validate password
- [x] when choosing to signup from the sign in modal open a sign up modal instead of a redirect to signup page
- [x] show validation errors inside the form instead of an alert message

# Utility - back
- [x] create new recipe
- [x] delete recipe
- [x] change recipe
- [x] upload photo
- [x] search recipes
- [x] filter recipes by category
- [x] authentication
- [x] add toggle dir rtl to editor --- each editor has a rtl bool and if its not false when it returns to parent recipe editor then the main rtl var will be changed to true.
