### ISSUE TITLE
todo auth

### ISSUE THREAD

**Issue by YotamGit** [YotamGit/recipe-app#12]
# client
- [x] send cookie in request headers instead of params
- [x]  send cookie with each delete and update request to prevent unauthorized edits
- [x] fix issue where reload of page quickly redirects from login to the same page
- [x] if unauthorized on each request redirect to login.

# server
- [x] check on the update and delete methods that the cookie contains the right password
- [x] add login middleware that checks the cookie password - if unauthorized send 401
