### ISSUE TITLE
TODO: Users

### ISSUE THREAD

**Issue by YotamGit** [YotamGit/recipe-app#17]
- [x] user based login
- [x] each user can sign up with his own password
- [ ] add option to retrieve lost password(?)
- [x] each recipe has a creator
- [x] each recipe has an array of users that liked the recipe
- [x] add a user collection to db
- [x] validate username
- [x] validate password
- [ ] when choosing to signup from the sign in modal open a sign up modal instead of a redirect to signup page
- [ ] show validation errors inside the form instead of an alert message
